sudo: required
language: bash
services:
- docker
install:
- docker pull multiarch/qemu-user-static:register
- docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
- echo "$TRAVIS_BRANCH"
- if [ "$TRAVIS_BRANCH" != "master" ]; then make build KERNEL=x86_64/4.4.34-docker/; fi

