sudo: required
language: bash
addons:
  ssh_known_hosts: kernel.innovatete.ch
services:
- docker
install:
- docker pull multiarch/qemu-user-static:register
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- mkdir ~/.ssh || true
- echo $SSH_KEY > ~/.ssh/id_rsa

script:
- if [ "$TRAVIS_BRANCH" == "master" ]; ssh travis@kernel.innovatete.ch "echo ok"; fi
- if [ "$TRAVIS_BRANCH" != "master" ]; then make build KERNEL=x86_64/4.4.34-docker/; fi
- if [ "$TRAVIS_BRANCH" != "master" ]; scp -r ./dist/* travis@kernel.innovatete.ch:/var/www/html/4.4.34-docker-x86_64/; fi



