sudo: required
language: bash
addons:
  ssh_known_hosts: kernel.innovatete.ch
services:
- docker
install:
- docker pull multiarch/qemu-user-static:register
- docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
- if [ "$TRAVIS_BRANCH" != "master" ]; then make build KERNEL=x86_64/4.4.34-docker/; fi


